// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package destination

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"auth.password": {
			Default:     "",
			Description: "The password to use when performing basic auth.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"auth.realm": {
			Default:     "",
			Description: "The realm to use when performing basic auth.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"auth.username": {
			Default:     "",
			Description: "The username to use when performing basic auth.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"database": {
			Default:     "neo4j",
			Description: "The name of a database the connector should work with.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"entityLabels": {
			Default:     "",
			Description: "Holds a list of labels belonging to an entity.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"entityType": {
			Default:     "",
			Description: "Defines an entity type the connector should work with.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
				sdk.ValidationInclusion{List: []string{"node", "relationship"}},
			},
		},
		"uri": {
			Default:     "",
			Description: "The connection uri pointed to a Neo4j instance.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
