// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/conduitio/conduit-connector-sdk/cmd/paramgen

package destination

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"auth.password": {
			Default:     "",
			Description: "The password to use when performing basic auth.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"auth.realm": {
			Default:     "",
			Description: "The realm to use when performing basic auth.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"auth.username": {
			Default:     "",
			Description: "The username to use when performing basic auth.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"database": {
			Default:     "neo4j",
			Description: "The name of a database the connector should work with.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"keyProperties": {
			Default:     "",
			Description: "The comma separated list of column names to build a WHERE clause in case sdk.Record.Key is empty (destination) or build an sdk.Record.Key (source).",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"uri": {
			Default:     "",
			Description: "The connection uri pointed to a Neo4j instance.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
