// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/conduitio/conduit-connector-sdk/cmd/paramgen

package source

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"auth.password": {
			Default:     "",
			Description: "The password to use when performing basic auth.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"auth.realm": {
			Default:     "",
			Description: "The realm to use when performing basic auth.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"auth.username": {
			Default:     "",
			Description: "The username to use when performing basic auth.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"batchSize": {
			Default:     "1000",
			Description: "The size of an element batch.",
			Type:        sdk.ParameterTypeInt,
			Validations: []sdk.Validation{
				sdk.ValidationGreaterThan{Value: 0},
				sdk.ValidationLessThan{Value: 100001},
			},
		},
		"database": {
			Default:     "neo4j",
			Description: "The name of a database the connector should work with.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"entityLabels": {
			Default:     "",
			Description: "Holds a list of labels belonging to an entity.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"entityType": {
			Default:     "",
			Description: "Defines an entity type the connector should work with.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
				sdk.ValidationInclusion{List: []string{"node", "relationship"}},
			},
		},
		"keyProperties": {
			Default:     "",
			Description: "The list of property names that are used for constructing a record key.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"orderingProperty": {
			Default:     "",
			Description: "The name of a property that is used for ordering nodes or relationships when capturing a snapshot.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"snapshot": {
			Default:     "true",
			Description: "Determines whether or not the connector will take a snapshot of all nodes or relationships before starting CDC mode.",
			Type:        sdk.ParameterTypeBool,
			Validations: []sdk.Validation{},
		},
		"uri": {
			Default:     "",
			Description: "The connection uri pointed to a Neo4j instance.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
